priorityClasses:
  - name: medium
    description: "Default priority class for all Pods. Does preempt lower priority Pods."
    globalDefault: true
    preemptionPolicy: PreemptLowerPriority
    value: 500000