# Helm chart values
prometheus:
  prometheusSpec:
    additionalAlertManagerConfigsSecret:
      name: alertmanager-pagerduty-secret
      key: pagerduty_key
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'pagerduty'

    receivers:
      - name: 'pagerduty'
        pagerduty_configs:
          - service_key_file: /etc/secrets/pagerduty/pagerduty_key
