# Helm chart values
alertmanager:
  extraSecretMounts:
    - name: alertmanager-pagerduty-plain-secret
      mountPath: /etc/alertmanager-pagerduty-plain-secret
      subPath: ""
      secretName: alertmanager-pagerduty-plain-secret
      readOnly: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'pagerduty'

    receivers:
      - name: 'pagerduty'
        pagerduty_configs:
          - service_key_file: /etc/alertmanager-pagerduty-plain-secret/pagerduty_key
