# Helm chart values
alertmanager:
  alertmanagerSpec:
    secrets:
      - alertmanager-pagerduty-plain-secret
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'pagerduty'

    receivers:
      - name: 'pagerduty'
        pagerduty_configs:
          - routing_key_file: '/etc/alertmanager/secrets/alertmanager-pagerduty-plain-secret/pagerduty_key'
